language: node_js

node_js:
  - stable

services:
  - docker

before_install:
- docker pull verdaccio/verdaccio:2.7.4
- docker run --name registry-npm -d -p 127.0.0.1:4873:4873  verdaccio/verdaccio:2.7.4

install:
  - npm install

script:
#  - npm run test:cover
  - npm run spec -- --registry=http://127.0.0.1:4873
  
after_failure:
  - npm logs registry-npm

#after_script:
#  - npm run test:cover:publish
