language: node_js

node_js:
  - stable

services:
  - docker

before_install:
- docker pull verdaccio/verdaccio:2.7.4
- docker run -d -p 127.0.0.1:4873:4873  verdaccio/verdaccio:2.7.4
- docker ps -a

#install:
#  - npm install

script:
  - sleep 10s
  - curl http://127.0.0.0:4873
#  - npm run test:cover
#  - npm run spec

#after_script:
#  - npm run test:cover:publish
